### ISSUE TITLE
Not updating the DataStore if we have the data in Datastore and having the updates in statsig gates.

### ISSUE THREAD

**Issue by Krishnamohan-Inovalon** [statsig-io/dotnet-sdk#35]
Add redis as data store for StatsigServer, and add a feature gate.
Initialize it once per application startup.
Now we can see the data added in redis (we dont have expiration time).
And now update the data in statsig feature gate rules, its not updated in redis and Evaluating against the stale data.

If we set the expiration time in Redis cache key statsig.cache lets say 5min, after that data is clearing in redis and we are making network calls instead of adding/updating the redis cache.

**Comment by tore-statsig** [comment]
Thanks for the report, we will look into this.  The sdk should be updating the redis data store

https://github.com/statsig-io/dotnet-sdk/blob/37d5e1d704a3668fe1e7ca9f4f798e6124eb17ea/dotnet-statsig/src/Statsig/Server/Evaluation/SpecStore.cs#L372

(note that this wont happen immediately, but should happen within 10s in the background)

But we can try to reproduce what you've described

**Comment by Krishnamohan-Inovalon** [comment]
![image](https://github.com/statsig-io/dotnet-sdk/assets/150655130/8cc1cbdf-1731-4dd8-9576-8fd4d2a9e989)
Issue1:If we have data in Redis, we are not making n/w calls though we have updated Feature Gates.

![image](https://github.com/statsig-io/dotnet-sdk/assets/150655130/517a5ba3-1614-4c82-a2a7-c9bf978f7ba1)

Issue2:If we set expiration time for Redis keys, we are adding/updating Redis only if we have updates in feature gates otherwise we are making n/w calls. In this case better to update Redis, and read from it instead of making n/w calls.

**Comment by sroyal-statsig** [comment]
@Krishnamohan-Inovalon are you setting the AllowConfigSpecPolling to true on the RedisDataStore? If that is true we will never do a network request and expect you to be updating the datastore with another service.
