### ISSUE TITLE
Switch to license expression & set repo url

### ISSUE THREAD

**Issue by thompson-tomo** [statsig-io/dotnet-sdk#38]
### Summary
I wish for the nuget packages to have the licence expression property set correctly and the repository url

### Details

The licence expression property should be set to the correct licence type I.e. Apache-2.0 as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc. By providing the repo url it will make it easier to contribute and can be used by source-link.

**Comment by kenny-statsig** [comment]
Hey @thompson-tomo we can patch in the repository URL but will leave the license as is. I'd prefer to point to the same license in Github

**Comment by thompson-tomo** [comment]
@kenny-statsig the issue is external tools can not then do license analysis of the libraries being used. My workplace do that for all developments hence are needing a license expression. At the same time it improves the developer expereicence in NUGET as easily instantly visible what type of license applies, hence would suggest reconsidering this.

**Comment by tore-statsig** [comment]
Reopening until this is complete.  Adding the license should be fine, but this repository (and all of our SDKs) are under the ISC license, not MIT

**Comment by thompson-tomo** [comment]
My apologies @tore-statsig not sure how I made that mistake but will correct it
