### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [statsig-io/dotnet-sdk#39]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want System.Net.Http to only be a dependency when it needs to be, this will reduce maintenance effort. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by kenny-statsig** [comment]
@thompson-tomo Thanks for the suggestion but im going to have to reject this request as we currently don't have the bandwidth to validate your change.

**Comment by thompson-tomo** [comment]
@kenny-statsig i am not sure what u mean necessary bandwidth. All that needs to happen is go to https://apisof.net/ or more preciously https://apisof.net/catalog/0d36ba651c900e3f96e5970abfecae5d at which point you will see that the dependency which is now conditional is already available as part of the framework. Alternatively you can expand the framework in Visual studio at which point you will also see that the library is automatically included as part of the framework. This is microsoft recommended approach as force you wouldn't add a reference to System.IO because the framework provides it, and it is the same here.
